language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry
  - poetry config virtualenvs.in-project true
install:
  - poetry install --extras "test"
script:
  - poetry run pytest
after_success:
  - poetry run coveralls
before_deploy:
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry build -f sdist
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true # only deploy on tagged commits
    branch: master
    repo: servian/bigquery-view-analyzer
    python: "3.7"
